### ISSUE TITLE
Generalize (re)render method

### ISSUE THREAD

**Issue by markus-walther** [cloudspeech/sig-nal#4]
<img width="627" alt="Screenshot 2024-05-27 at 15 05 16" src="https://github.com/cloudspeech/sig-nal/assets/46926507/420d1b58-f49a-42c8-b8f2-e6ad55534837">

The static `render` and `rerender` methods of &lt;sig-nal&gt; are great, except for when we want to do _more_ than assign to a property of a DOM node.

Take the case of manipulating the `.classList` property: instead of assignment, you choose a method (e.g. `toggle`) and supply a parameter (the class name as a string literal), then _invoke_ said method.

We can generalize things if we can supply an _optional_ transform function (default: the existing assignment).

The new `rerender(transform)` signature would be backwards incompatible with respect to existing hydration specs: we would now need to specify `rerender()` function _application_ in all those places where hydration specs previously used just `rerender`, i.e. mere reference to the function _without._ application.

The classList case would use e.g. 
```js
rerender(({domNode, name, signal}) => domNode[name].toggle(signal.value))
```
Think this through a bit more.

Then implement it!

**Comment by cloudspeech** [comment]
It seems better w.r.t. backwards compatibility and simplicity for simple cases to _not_ extend rerender.

Instead, I propose to implement a new method **renderWith**({type,name, signal, signals, init, kind, domNode, domNodes, e) => /* callback body */).

The classList case would then be

```js
renderWith(({domNode, name, signal}) => domNode[name].toggle(signal.value))
```
